### ISSUE TITLE
Error while uploading image

### ISSUE THREAD

**Issue by lahirukawijes** [tarique93102/image-upload-app#1]
hello sir,
i was following your [tutorial](https://codeburst.io/image-uploading-using-react-and-node-to-get-the-images-up-c46ec11a7129)
but i get an error. any idea?

**Comment by tejazz** [comment]
I am really sorry to hear that. Can you tell me more about the error you are facing?

**Comment by lahirukawijes** [comment]
Thank you very much sir for your quick reply.

![WhatsApp Image 2019-11-17 at 6 31 21 PM](https://user-images.githubusercontent.com/36619863/69007790-87ee1f80-0968-11ea-8de8-57d3b894b695.jpeg)

herewith I have attached a screenshot.
I was trying to extract the multer and mongoDB part.
and here is [my version of code](https://github.com/lahirukawijes/image-upload-app/tree/test-1)

**Comment by tejazz** [comment]
Hello,

I just reran your code. You have missed out on creating a static /uploads
folder in your node directory.

That would solve the problem.

Regards,
Tarique

[image: image.png]
